### PR TITLE
Exclude deploy directory for FileName cop.

### PR DESCRIPTION
**Pull request by xzile**

### CODE REVIEW

**Comment by dzajic** [comment]
So this is because of things like `sandbox-old.rb`?

**Comment by xzile** [comment]
Yeah.  The exclude is just for files in that directory.

**Comment by dzajic** [comment]
I'd love to have the background on that, in the exclusion comment, i.e. why do the filenames need dashes, and/or is it a legacy thing that we won't need at some point?

**Comment by xzile** [comment]
I believe these deploy files are used for capistrano to do the actual deploys.  After that, I don't know much.

**Review by tobyond — APPROVED** [review]
good call, this is unlikely to meet standards

**Pull request merged**
